// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKfHmc1VItibmhXVCZnFHrID4JutdWy8c',
    appId: '1:475508724472:web:7acc5d9ae045d3b9a8e10d',
    messagingSenderId: '475508724472',
    projectId: 'pharmacyplatform-45bdc',
    authDomain: 'pharmacyplatform-45bdc.firebaseapp.com',
    storageBucket: 'pharmacyplatform-45bdc.appspot.com',
    measurementId: 'G-24M5SKQBHB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKj0lF9DZSfNAVctHgUmd4CbmJmsoCD-Y',
    appId: '1:475508724472:android:3011e21cd130fc23a8e10d',
    messagingSenderId: '475508724472',
    projectId: 'pharmacyplatform-45bdc',
    storageBucket: 'pharmacyplatform-45bdc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtQNhgE1o_Grv_wTEhw0gOV82qeaR5ZS4',
    appId: '1:475508724472:ios:f1c6934a5207449fa8e10d',
    messagingSenderId: '475508724472',
    projectId: 'pharmacyplatform-45bdc',
    storageBucket: 'pharmacyplatform-45bdc.appspot.com',
    iosClientId: '475508724472-574p5c4if1v7sgousrgdc86vljir0mtf.apps.googleusercontent.com',
    iosBundleId: 'com.example.pharmacyPlateform',
  );
}
